import { useAppSettings } from '@/components/providers/AppSettingsProvider'

const COPY = {
  en: {
    nav: {
      dashboard: 'Overview',
      transactions: 'Transactions',
      budget: 'Budget',
      categories: 'Categories',
      reports: 'Reports',
      import: 'Import',
      signOut: 'Sign out',
      lightMode: 'Light mode',
      darkMode: 'Dark mode',
      switchToLight: 'Switch to light mode',
      switchToDark: 'Switch to dark mode',
    },
    login: {
      subtitle: 'Sign in with your Supabase account to continue.',
      password: 'Password',
      signIn: 'Sign in',
      signingIn: 'Signing in...',
      invalidCredentials: 'Incorrect email or password.',
    },
    setup: {
      eyebrow: 'First-run setup',
      title: 'Configure your own household budget workspace.',
      body: 'This starter is designed for one household per deployment. Choose your defaults, then decide whether you want a blank app or a prebuilt budget template.',
      startBlank: 'Start blank',
      startBlankDescription: 'No categories, no budgets, and no starter rules.',
      starterTemplate: 'Use starter template',
      starterTemplateDescription: 'Create common categories and a few starter categorization rules.',
      detailsTitle: 'Workspace details',
      detailsBody: 'These values control branding, formatting, and starter content.',
      appName: 'App name',
      householdName: 'Household name',
      locale: 'Locale',
      currency: 'Default currency',
      timezone: 'Timezone',
      householdSize: 'Household size',
      starterBudget: 'Create starter monthly budgets for the current month.',
      finish: 'Finish setup',
      saving: 'Saving setup...',
      saveError: 'Unable to save setup.',
    },
    dashboard: {
      title: 'Dashboard',
      subtitle: 'Budget versus actual spending for',
      addExpense: 'Add expense',
      currentMonth: 'Current month',
      noBudget: 'No budget has been configured for this month yet.',
      setupBudget: 'Set up budget',
      overBudget: 'Over budget',
      in: 'in',
      spent: 'Spent',
      budget: 'Budget',
      monthlyTotal: 'Monthly total',
      remaining: 'Remaining',
      over: 'Over',
      underBudget: 'Under budget',
      overBudgetLabel: 'Over budget',
      perPerson: 'Per person',
      of: 'of',
      byCategory: 'By category',
      watch: 'Watch',
      review: 'Review',
      uncategorized: 'uncategorized transactions',
      uncategorizedOne: 'uncategorized transaction',
      recentTransactions: 'Recent transactions',
      viewAll: 'View all',
    },
    budget: {
      title: 'Monthly budget',
      subtitle: 'Plan how much you expect to spend in each category.',
      copyPrevious: 'Copy previous month',
      copying: 'Copying...',
      applyMultiple: 'Apply to multiple months',
      copyFrom: 'Copy the budget from',
      to: 'to',
      selectAll: 'Select all',
      clearAll: 'Clear all',
      applied: 'Budget applied to',
      month: 'month',
      months: 'months',
      applying: 'Applying',
      applyTo: 'Apply to',
      close: 'Close',
      categories: 'Budget categories',
      monthlyTotal: 'Monthly total',
      perPerson: 'Per person',
      saved: 'Saved',
      saving: 'Saving...',
      saveBudget: 'Save budget',
      noSavedBudget: 'No saved budget found for',
      unableCopy: 'Unable to copy the previous month.',
    },
    transactions: {
      title: 'Transactions',
      inExpenses: 'in expenses',
      addManual: 'Add manual',
      all: 'All',
      allCategories: 'All categories',
      searchMerchant: 'Search merchant...',
      noCategory: 'No category',
      date: 'Date',
      description: 'Description',
      category: 'Category',
      amount: 'Amount',
      notes: 'Notes',
      loading: 'Loading...',
      noMatches: 'No transactions matched this filter.',
      page: 'Page',
      of: 'of',
      splitAnnualTitle: 'Annual expense split across 12 months',
    },
    categories: {
      title: 'Categories and rules',
      subtitle: 'Manage manual categories and auto-categorization rules.',
      categories: 'Categories',
      new: 'New',
      create: 'Create',
      saving: 'Saving...',
      cancel: 'Cancel',
      income: 'Income',
      expense: 'Expense',
      markExpense: 'Mark as expense',
      markIncome: 'Mark as income',
      edit: 'Edit',
      delete: 'Delete',
      deleteConfirmPrefix: 'Delete category',
      deleteConfirmSuffix: 'Existing transactions will lose this category.',
      deleteError: 'Unable to delete the category.',
      noRules: 'No rules yet. Add one to categorize future transactions automatically.',
      rulesFor: 'Rules for',
      addRule: 'Add rule',
      type: 'Type',
      contains: 'Contains',
      exact: 'Exact match',
      startsWith: 'Starts with',
      value: 'Value',
      exampleMerchant: 'Example: uber eats',
      priority: 'Priority',
      notesOptional: 'Notes (optional)',
      optionalDescription: 'Optional description...',
      testRules: 'Test rules',
      typeMerchantDescription: 'Type a merchant description...',
      test: 'Test',
      matchesCategory: 'Matches category:',
      rule: 'Rule:',
      priorityLabel: 'priority',
      noRuleMatched: 'No rule matched this description.',
      disable: 'Disable',
      enable: 'Enable',
    },
    reports: {
      title: 'Reports',
      subtitle: 'View monthly and yearly spending trends.',
      monthly: 'Monthly',
      yearly: 'Yearly',
      loading: 'Loading...',
      noData: 'No data is available for this month yet.',
      spent: 'Spent',
      budget: 'Budget',
      plannedTotal: 'Planned total',
      remaining: 'Remaining',
      over: 'Over',
      underBudget: 'Under budget',
      overBudget: 'Over budget',
      perPerson: 'Per person',
      of: 'of',
      byCategory: 'By category',
      distribution: 'Distribution',
      noSpending: 'No spending this month',
      moreCategories: 'more categories',
      totalSpendingByMonth: 'Total spending by month',
      totalSpent: 'Total spent',
      monthlyAverage: 'Monthly average',
      monthsWithData: 'months with data',
      perPersonYear: 'Per person / year',
      watch: 'Watch',
    },
    import: {
      title: 'Import statement',
      subtitle: 'Upload a CSV statement to import your latest transactions.',
      completed: 'Import completed',
      imported: 'Imported',
      duplicates: 'Duplicates',
      errors: 'Errors',
      importAnother: 'Import another file',
      viewTransactions: 'View transactions',
      dropCsv: 'Drop a CSV statement here',
      clickBrowse: 'or click to browse',
      validRows: 'valid rows',
      skipped: 'skipped',
      date: 'Date',
      description: 'Description',
      type: 'Type',
      amount: 'Amount',
      importing: 'Importing...',
      importCount: 'Import',
      cancel: 'Cancel',
      howToExport: 'CSV import notes',
      steps: [
        'The current parser is optimized for Revolut-style CSV exports.',
        'If your bank exports a CSV with similar columns, it may work.',
        'Support for arbitrary bank formats is not guaranteed yet.',
        'Recommended flow: export your account statement as CSV.',
        'Then upload that file here.',
      ],
      importFailed: 'Import failed.',
      networkError: 'Network error during import.',
    },
    addTx: {
      title: 'Add manual expense',
      description: 'Description',
      amount: 'Amount',
      date: 'Date',
      category: 'Category',
      selectCategory: 'Select a category...',
      notes: 'Notes (optional)',
      notesPlaceholder: 'Any extra context...',
      cancel: 'Cancel',
      save: 'Save',
      saving: 'Saving...',
      required: 'Description, amount, and date are required.',
      invalidAmount: 'Invalid amount.',
      saveError: 'Unable to save transaction.',
    },
    editTx: {
      title: 'Edit transaction',
      expense: 'Expense',
      income: 'Income',
      savedRule: 'Saved rule:',
      alsoUpdated: 'Also updated',
      moreTransactions: 'more transactions with the same description.',
      category: 'Category',
      noCategory: 'No category',
      notes: 'Notes',
      addNote: 'Add a note...',
      spread: 'Spread across 12 months',
      perMonth: '/month',
      annualHint: 'Treat this as an annual expense in the monthly budget',
      assignAnotherMonth: 'Assign to another month',
      trackedIn: 'Tracked in',
      autoMonth: 'Use the transaction month automatically',
      excludeBudget: 'Exclude from budget',
      excludeHint: 'Ignore exceptional one-off spending in the budget totals',
      saveChanges: 'Save changes',
      saving: 'Saving...',
      cancel: 'Cancel',
      deleteTransaction: 'Delete transaction',
      deleteConfirm: 'Delete this transaction?',
      deleting: 'Deleting...',
      yesDelete: 'Yes, delete',
    },
  },
  es: {
    nav: {
      dashboard: 'Resumen',
      transactions: 'Transacciones',
      budget: 'Presupuesto',
      categories: 'Categorías',
      reports: 'Informes',
      import: 'Importar',
      signOut: 'Cerrar sesión',
      lightMode: 'Modo claro',
      darkMode: 'Modo oscuro',
      switchToLight: 'Cambiar a modo claro',
      switchToDark: 'Cambiar a modo oscuro',
    },
    login: {
      subtitle: 'Inicia sesión con tu cuenta de Supabase para continuar.',
      password: 'Contraseña',
      signIn: 'Entrar',
      signingIn: 'Entrando...',
      invalidCredentials: 'Email o contraseña incorrectos.',
    },
    setup: {
      eyebrow: 'Configuración inicial',
      title: 'Configura tu propio espacio de presupuesto familiar.',
      body: 'Este starter está pensado para un solo hogar por despliegue. Elige tus valores por defecto y decide si quieres una app vacía o una plantilla inicial.',
      startBlank: 'Empezar en blanco',
      startBlankDescription: 'Sin categorías, sin presupuestos y sin reglas iniciales.',
      starterTemplate: 'Usar plantilla inicial',
      starterTemplateDescription: 'Crea categorías comunes y algunas reglas de categorización.',
      detailsTitle: 'Detalles del espacio',
      detailsBody: 'Estos valores controlan la marca, el formato y el contenido inicial.',
      appName: 'Nombre de la app',
      householdName: 'Nombre del hogar',
      locale: 'Idioma y región',
      currency: 'Divisa por defecto',
      timezone: 'Zona horaria',
      householdSize: 'Tamaño del hogar',
      starterBudget: 'Crear presupuestos iniciales para el mes actual.',
      finish: 'Terminar configuración',
      saving: 'Guardando configuración...',
      saveError: 'No se pudo guardar la configuración.',
    },
    dashboard: {
      title: 'Resumen',
      subtitle: 'Comparativa entre presupuesto y gasto real de',
      addExpense: 'Añadir gasto',
      currentMonth: 'Mes actual',
      noBudget: 'No hay presupuesto configurado para este mes.',
      setupBudget: 'Configurar presupuesto',
      overBudget: 'Presupuesto superado',
      in: 'en',
      spent: 'Gastado',
      budget: 'Presupuesto',
      monthlyTotal: 'Total mensual',
      remaining: 'Ahorro',
      over: 'Exceso',
      underBudget: 'Bajo presupuesto',
      overBudgetLabel: 'Sobre presupuesto',
      perPerson: 'Por persona',
      of: 'de',
      byCategory: 'Por categoría',
      watch: 'Atención',
      review: 'Revisar',
      uncategorized: 'transacciones sin categorizar',
      uncategorizedOne: 'transacción sin categorizar',
      recentTransactions: 'Últimas transacciones',
      viewAll: 'Ver todas',
    },
    budget: {
      title: 'Presupuesto mensual',
      subtitle: 'Planifica cuánto esperas gastar en cada categoría.',
      copyPrevious: 'Copiar mes anterior',
      copying: 'Copiando...',
      applyMultiple: 'Aplicar a varios meses',
      copyFrom: 'Copiar el presupuesto de',
      to: 'a',
      selectAll: 'Marcar todo',
      clearAll: 'Desmarcar todo',
      applied: 'Presupuesto aplicado a',
      month: 'mes',
      months: 'meses',
      applying: 'Aplicando',
      applyTo: 'Aplicar a',
      close: 'Cerrar',
      categories: 'Partidas presupuestarias',
      monthlyTotal: 'Total mensual',
      perPerson: 'Por persona',
      saved: 'Guardado',
      saving: 'Guardando...',
      saveBudget: 'Guardar presupuesto',
      noSavedBudget: 'No hay presupuesto guardado para',
      unableCopy: 'No se pudo copiar el mes anterior.',
    },
    transactions: {
      title: 'Transacciones',
      inExpenses: 'en gastos',
      addManual: 'Añadir manual',
      all: 'Todas',
      allCategories: 'Todas las categorías',
      searchMerchant: 'Buscar comercio...',
      noCategory: 'Sin categoría',
      date: 'Fecha',
      description: 'Descripción',
      category: 'Categoría',
      amount: 'Importe',
      notes: 'Notas',
      loading: 'Cargando...',
      noMatches: 'No hay transacciones para este filtro.',
      page: 'Página',
      of: 'de',
      splitAnnualTitle: 'Gasto anual prorrateado entre 12 meses',
    },
    categories: {
      title: 'Categorías y reglas',
      subtitle: 'Gestiona categorías manuales y reglas de categorización automática.',
      categories: 'Categorías',
      new: 'Nueva',
      create: 'Crear',
      saving: 'Guardando...',
      cancel: 'Cancelar',
      income: 'Ingreso',
      expense: 'Gasto',
      markExpense: 'Marcar como gasto',
      markIncome: 'Marcar como ingreso',
      edit: 'Editar',
      delete: 'Eliminar',
      deleteConfirmPrefix: 'Eliminar la categoría',
      deleteConfirmSuffix: 'Las transacciones perderán esta categoría.',
      deleteError: 'No se pudo eliminar la categoría.',
      noRules: 'No hay reglas todavía. Añade una para categorizar futuras transacciones automáticamente.',
      rulesFor: 'Reglas para',
      addRule: 'Añadir regla',
      type: 'Tipo',
      contains: 'Contiene',
      exact: 'Exacto',
      startsWith: 'Empieza con',
      value: 'Valor',
      exampleMerchant: 'Ej: uber eats',
      priority: 'Prioridad',
      notesOptional: 'Notas (opcional)',
      optionalDescription: 'Descripción opcional...',
      testRules: 'Probar reglas',
      typeMerchantDescription: 'Escribe una descripción del comercio...',
      test: 'Probar',
      matchesCategory: 'Coincide con categoría:',
      rule: 'Regla:',
      priorityLabel: 'prioridad',
      noRuleMatched: 'Ninguna regla coincide con esta descripción.',
      disable: 'Desactivar',
      enable: 'Activar',
    },
    reports: {
      title: 'Informes',
      subtitle: 'Consulta la evolución mensual y anual de tus gastos.',
      monthly: 'Mensual',
      yearly: 'Anual',
      loading: 'Cargando...',
      noData: 'No hay datos para este mes.',
      spent: 'Gastado',
      budget: 'Presupuesto',
      plannedTotal: 'Total planificado',
      remaining: 'Ahorro',
      over: 'Exceso',
      underBudget: 'Bajo presupuesto',
      overBudget: 'Presupuesto superado',
      perPerson: 'Por persona',
      of: 'de',
      byCategory: 'Por categoría',
      distribution: 'Distribución',
      noSpending: 'Sin gastos este mes',
      moreCategories: 'categorías más',
      totalSpendingByMonth: 'Gasto total por mes',
      totalSpent: 'Total gastado',
      monthlyAverage: 'Media mensual',
      monthsWithData: 'meses con datos',
      perPersonYear: 'Por persona / año',
      watch: 'Atención',
    },
    import: {
      title: 'Importar extracto',
      subtitle: 'Sube un extracto CSV para importar tus últimas transacciones.',
      completed: 'Importación completada',
      imported: 'Importadas',
      duplicates: 'Duplicadas',
      errors: 'Errores',
      importAnother: 'Importar otro archivo',
      viewTransactions: 'Ver transacciones',
      dropCsv: 'Arrastra aquí un extracto CSV',
      clickBrowse: 'o haz clic para seleccionar',
      validRows: 'filas válidas',
      skipped: 'omitidas',
      date: 'Fecha',
      description: 'Descripción',
      type: 'Tipo',
      amount: 'Importe',
      importing: 'Importando...',
      importCount: 'Importar',
      cancel: 'Cancelar',
      howToExport: 'Notas sobre la importación CSV',
      steps: [
        'El parser actual está optimizado para CSV con formato similar a Revolut.',
        'Si tu banco exporta un CSV con columnas parecidas, puede funcionar.',
        'El soporte para formatos arbitrarios de otros bancos aún no está garantizado.',
        'Flujo recomendado: exporta el extracto de tu cuenta como CSV.',
        'Después sube ese archivo aquí.',
      ],
      importFailed: 'La importación ha fallado.',
      networkError: 'Error de red durante la importación.',
    },
    addTx: {
      title: 'Añadir gasto manual',
      description: 'Descripción',
      amount: 'Importe',
      date: 'Fecha',
      category: 'Categoría',
      selectCategory: 'Selecciona una categoría...',
      notes: 'Notas (opcional)',
      notesPlaceholder: 'Cualquier detalle extra...',
      cancel: 'Cancelar',
      save: 'Guardar',
      saving: 'Guardando...',
      required: 'Descripción, importe y fecha son obligatorios.',
      invalidAmount: 'Importe inválido.',
      saveError: 'No se pudo guardar la transacción.',
    },
    editTx: {
      title: 'Editar transacción',
      expense: 'Gasto',
      income: 'Ingreso',
      savedRule: 'Regla guardada:',
      alsoUpdated: 'También se actualizaron',
      moreTransactions: 'transacciones más con la misma descripción.',
      category: 'Categoría',
      noCategory: 'Sin categoría',
      notes: 'Notas',
      addNote: 'Añade una nota...',
      spread: 'Prorratear en 12 meses',
      perMonth: '/mes',
      annualHint: 'Trata esto como un gasto anual dentro del presupuesto mensual',
      assignAnotherMonth: 'Imputar a otro mes',
      trackedIn: 'Imputado en',
      autoMonth: 'Usar automáticamente el mes de la transacción',
      excludeBudget: 'Excluir del presupuesto',
      excludeHint: 'Ignora gastos excepcionales en los totales del presupuesto',
      saveChanges: 'Guardar cambios',
      saving: 'Guardando...',
      cancel: 'Cancelar',
      deleteTransaction: 'Eliminar transacción',
      deleteConfirm: '¿Eliminar esta transacción?',
      deleting: 'Eliminando...',
      yesDelete: 'Sí, eliminar',
    },
  },
} as const

export function getUiCopy(locale: string) {
  return locale.startsWith('es') ? COPY.es : COPY.en
}

export function useUiCopy() {
  const settings = useAppSettings()
  return getUiCopy(settings.locale)
}
